import { afterEach, expect, it, vi } from "vitest";
import { createRequire } from "node:module";
import type { EmbeddingStore } from "./embedding-store";
type Database = EmbeddingStore & {close():void};
const {DatabaseSync}=createRequire(import.meta.url)("node:sqlite") as {DatabaseSync:new(file:string)=>Database};
import { createQueryEmbeddingSession } from "./query-embedding";
import { createBookRetrieval } from "./book-retrieval";
import { buildVectorBatch } from "./vector-index";
import type { searchVectors } from "./vector-search";
const databases:Database[]=[];afterEach(()=>databases.splice(0).forEach(db=>db.close()));
async function setup(){const db=new DatabaseSync(":memory:");databases.push(db);db.exec("CREATE TABLE editions(id TEXT);CREATE TABLE chapters(id TEXT,edition_id TEXT,title TEXT,order_index INTEGER);CREATE TABLE paragraphs(id TEXT,chapter_id TEXT,text TEXT,order_index INTEGER);INSERT INTO editions VALUES('e');INSERT INTO chapters VALUES('c','e','章节',0),('other','other','别书',0);INSERT INTO paragraphs VALUES('p','c','猫喜欢晒太阳。',0),('x','other','猫喜欢晒太阳。',0)");await buildVectorBatch(db,'e',{apiKey:'fake'},undefined,async(_c,texts)=>texts.map(()=>[1,...Array<number>(1023).fill(0)]));return db;}
it("多个语义查询并行且与关键词融合，严格保留版本及原文",async()=>{const db=await setup();const resolvers:(()=>void)[]=[];const vector=vi.fn<typeof searchVectors>(async()=>{await new Promise<void>(r=>resolvers.push(r));return [{paragraphId:'p',chapterId:'c',chapterTitle:'章节',paragraphIndex:0,matchedText:'猫喜欢晒太阳。',startOffset:0,endOffset:7,excerpt:'猫喜欢晒太阳。',context:{before:[],after:[]},retrieval:{backend:'sqlite',keywordScore:0,vectorSimilarity:.8,rrfScore:1,vectorUsed:true}}]});const search=createBookRetrieval({db,editionId:'e',embeddings:createQueryEmbeddingSession({apiKey:'fake'}),config:{apiKey:'fake'},vector});const pending=search({query:'动物休息',additionalQueries:['猫'],limit:5});expect(vector).toHaveBeenCalledTimes(2);resolvers.forEach(r=>r());const result=await pending;expect(result.retrieval.branches).toHaveLength(4);expect(result.sources.map(s=>s.paragraphId)).toEqual(['p']);expect(result.results[0].retrieval?.keywordScore).toBeGreaterThan(0);expect(result.retrieval.effectiveMode).toBe('hybrid');});
it("未配置与向量失败明确降级，强制语义不冒充成功",async()=>{const db=await setup();const vector=vi.fn<typeof searchVectors>().mockRejectedValue(new Error('private secret'));const search=createBookRetrieval({db,editionId:'e',embeddings:createQueryEmbeddingSession({apiKey:'fake'}),config:{apiKey:'fake'},vector});const result=await search({query:'猫',limit:5});expect(result.retrieval).toMatchObject({effectiveMode:'keyword',degraded:true});expect(JSON.stringify(result)).not.toContain('private secret');expect((await search({query:'猫',limit:5,mode:'semantic'})).retrieval.effectiveMode).toBe('none');const offline=createBookRetrieval({db,editionId:'e',embeddings:createQueryEmbeddingSession({apiKey:'fake'}),config:{apiKey:''},vector});expect((await offline({query:'猫',limit:5})).sources).toHaveLength(1);});
it("取消不降级为成功，章节过滤生效",async()=>{const db=await setup();const search=createBookRetrieval({db,editionId:'e',embeddings:createQueryEmbeddingSession({apiKey:'fake'}),config:{apiKey:''}});const controller=new AbortController();controller.abort();await expect(search({query:'猫',limit:5,signal:controller.signal})).rejects.toThrow();expect((await search({query:'猫',chapterId:'other',limit:5})).sources).toHaveLength(0);});

it("关闭自动语义不绕过用户选择，显式语义保留不可用报告",async()=>{const db=await setup();const vector=vi.fn<typeof searchVectors>();const search=createBookRetrieval({db,editionId:'e',config:{apiKey:'fake'},semanticEnabled:false,embeddings:createQueryEmbeddingSession({apiKey:'fake'}),vector});expect((await search({query:'猫',limit:5})).retrieval).toMatchObject({requestedMode:'auto',effectiveMode:'keyword',degraded:true});expect((await search({query:'猫',limit:5,mode:'semantic'})).retrieval.effectiveMode).toBe('none');expect(vector).not.toHaveBeenCalled();});
