export type ContextMessage = { role: "user" | "assistant"; content: string; id?: string };
export type ContextSettings = { maxInputTokens: number; maxOutputTokens: number; compressionStrategy: "conservative" | "balanced" | "aggressive" };
export type StructuredCompressionState = { task: string; decisions: string[]; conclusions: string[]; openQuestions: string[]; constraints: string[]; evidence: string[] };
export type CompactionSnapshot = { version: number; previousVersion: number | null; sourceMessageIds: string[]; summary: string; state: StructuredCompressionState; checksum: string; createdAt: string };
export type CompactedContext = { summary: string; messages: ContextMessage[]; estimatedTokens: number; compacted: boolean; trigger: "none" | "threshold"; snapshot?: CompactionSnapshot; version: number; previousVersion: number | null; sourceMessageIds: string[]; state: StructuredCompressionState; checksum: string };
export const DEFAULT_CONTEXT_SETTINGS: ContextSettings = { maxInputTokens: 32768, maxOutputTokens: 4096, compressionStrategy: "balanced" };
const EMPTY_STATE: StructuredCompressionState = { task: "", decisions: [], conclusions: [], openQuestions: [], constraints: [], evidence: [] };
export function estimateTokens(value: string): number { return Math.max(1, Math.ceil(Array.from(value).length / 2)); }
function clean(value: string): string { return value.replace(/\s+/g, " ").trim(); }
function unique(values: string[], limit: number): string[] { return [...new Set(values.map(clean).filter(Boolean))].slice(-limit); }
function buildState(messages: ContextMessage[]): StructuredCompressionState {
  const users = messages.filter((m) => m.role === "user").map((m) => clean(m.content));
  const assistants = messages.filter((m) => m.role === "assistant").map((m) => clean(m.content));
  return { task: users[0] ?? "", decisions: unique(users.filter((x) => /decide|confirm|adopt|choose|decision/i.test(x)), 8), conclusions: unique(assistants.filter((x) => /conclu|therefore|summary|complete|suggest/i.test(x)), 8), openQuestions: unique(users.filter((x) => /[?？]|how|why|whether/i.test(x)), 8), constraints: unique(users.filter((x) => /must|constraint|only|priority/i.test(x)), 8), evidence: unique(messages.flatMap((m) => [...m.content.matchAll(/(?:sourceId|paragraphId|textHash)[^,?\s]*/g)].map((x) => x[0])), 12) };
}
function renderState(state: StructuredCompressionState): string { const lines = ["structured context state:", `task: ${state.task || "unspecified"}`]; const groups: Array<[string, string[]]> = [["decisions", state.decisions], ["conclusions", state.conclusions], ["open questions", state.openQuestions], ["constraints", state.constraints], ["evidence", state.evidence]]; for (const [label, values] of groups) if (values.length) lines.push(`${label}: ${values.join("; ")}`); return lines.join("\n"); }
function digest(value: string): string { let hash = 2166136261; for (const char of value) { hash ^= char.codePointAt(0) ?? 0; hash = Math.imul(hash, 16777619); } return (hash >>> 0).toString(16).padStart(8, "0"); }
function base(messages: ContextMessage[], fixedContext: string): CompactedContext { const ids = messages.map((m, i) => m.id ?? `message-${i}`); return { summary: "", messages, estimatedTokens: estimateTokens([fixedContext, ...messages.map((m) => m.content)].join("\n")), compacted: false, trigger: "none", version: 0, previousVersion: null, sourceMessageIds: ids, state: EMPTY_STATE, checksum: digest(JSON.stringify({ ids, fixedContext })) }; }
export function compactContext(messages: ContextMessage[], settings: ContextSettings = DEFAULT_CONTEXT_SETTINGS, fixedContext = "", previousVersion: number | Pick<CompactedContext, "version"> | CompactionSnapshot = 0): CompactedContext {
  const safe = { ...DEFAULT_CONTEXT_SETTINGS, ...settings }; const threshold = safe.maxInputTokens * (safe.compressionStrategy === "conservative" ? 0.85 : safe.compressionStrategy === "aggressive" ? 0.65 : 0.75); const fullTokens = estimateTokens([fixedContext, ...messages.map((m) => m.content)].join("\n"));
  if (fullTokens <= threshold) return base(messages, fixedContext);
  const ratio = safe.compressionStrategy === "conservative" ? 0.5 : safe.compressionStrategy === "aggressive" ? 0.25 : 0.35; const target = Math.max(2, Math.floor(messages.length * ratio)); const older = messages.slice(0, -target); const recent = messages.slice(-target); const state = buildState(older); const summary = renderState(state); const sourceMessageIds = older.map((m, i) => m.id ?? `message-${i}`); const prior = typeof previousVersion === "number" ? previousVersion : previousVersion.version; const version = prior + 1;
  const checksum = digest(JSON.stringify({ version, prior, summary, sourceMessageIds, state, recent })); const snapshot: CompactionSnapshot = { version, previousVersion: prior || null, sourceMessageIds, summary, state, checksum, createdAt: new Date().toISOString() };
  return { summary, messages: recent, estimatedTokens: estimateTokens([fixedContext, summary, ...recent.map((m) => m.content)].join("\n")), compacted: true, trigger: "threshold", snapshot, version, previousVersion: prior || null, sourceMessageIds, state, checksum };
}
export function validateCompactedContext(value: unknown): value is CompactedContext { if (!value || typeof value !== "object") return false; const x = value as Partial<CompactedContext>; return typeof x.summary === "string" && Array.isArray(x.messages) && typeof x.estimatedTokens === "number" && typeof x.version === "number" && (x.previousVersion === null || typeof x.previousVersion === "number") && Array.isArray(x.sourceMessageIds) && typeof x.checksum === "string" && !!x.state && typeof x.state === "object"; }
