import {afterEach,expect,it,vi} from 'vitest';
import {createReaderOperationQueue,ReaderOperationTimeout,runReaderOperation} from './reader-operation';
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(cause:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no});return {promise,resolve,reject};}
afterEach(()=>vi.useRealTimers());
it('正常完成和原始错误都保留且清除计时器',async()=>{vi.useFakeTimers();const signal=new AbortController().signal;expect(await runReaderOperation(Promise.resolve(12),{signal,phase:'装配'})).toBe(12);const cause=new Error('具体失败');await expect(runReaderOperation(Promise.reject(cause),{signal,phase:'装配'})).rejects.toBe(cause);expect(vi.getTimerCount()).toBe(0);});
it('超时带阶段/类型，不改变20秒预算',async()=>{vi.useFakeTimers();const job=runReaderOperation(new Promise(()=>{}),{signal:new AbortController().signal,phase:'加载章节'});const assertion=expect(job).rejects.toMatchObject({name:'ReaderOperationTimeout',phase:'加载章节',code:'READER_OPERATION_TIMEOUT'});await vi.advanceTimersByTimeAsync(20000);await assertion;expect(vi.getTimerCount()).toBe(0);});
it('取消马上结束等待，迟到成功或失败都不能重新结算',async()=>{vi.useFakeTimers();for(const success of [true,false]){const task=deferred<number>(),controller=new AbortController(),job=runReaderOperation(task.promise,{signal:controller.signal,phase:'定位'});const assertion=expect(job).rejects.toMatchObject({name:'AbortError'});controller.abort();await assertion;if(success)task.resolve(3);else task.reject(new Error('迟到失败'));await Promise.resolve();expect(vi.getTimerCount()).toBe(0);}});
it('开始时已经取消也消费原任务的拒绝，不设置新timer',async()=>{vi.useFakeTimers();const controller=new AbortController();controller.abort();await expect(runReaderOperation(Promise.reject(new Error('旧错误')),{signal:controller.signal,phase:'读取'})).rejects.toMatchObject({name:'AbortError'});expect(vi.getTimerCount()).toBe(0);});
it('目录/翻页等待上一份导航结束，不同时进入renderer',async()=>{const first=deferred<void>(),steps:string[]=[],queue=createReaderOperationQueue(new AbortController().signal);const a=queue.run('目录',async()=>{steps.push('a');await first.promise;steps.push('a-end');});const b=queue.run('翻页',async()=>{steps.push('b');});await Promise.resolve();await Promise.resolve();expect(steps).toEqual(['a']);first.resolve();await Promise.all([a,b]);expect(steps).toEqual(['a','a-end','b']);});
it('关闭后排队操作不能启动，当前等待立即终止',async()=>{const controller=new AbortController(),queue=createReaderOperationQueue(controller.signal),next=vi.fn(async()=>{});const a=queue.run('初始化',()=>new Promise(()=>{})),b=queue.run('目录',next);const aa=expect(a).rejects.toMatchObject({name:'AbortError'}),bb=expect(b).rejects.toMatchObject({name:'AbortError'});await Promise.resolve();controller.abort();await aa;await bb;expect(next).not.toHaveBeenCalled();});
it('过期CFI普通错误可由调用方恢复，但超时可按类型拒绝重入',async()=>{const queue=createReaderOperationQueue(new AbortController().signal);await expect(queue.run('旧位置',async()=>{throw new Error('无效CFI');})).rejects.toThrow('无效CFI');expect(await queue.run('首章',async()=>1)).toBe(1);expect(new ReaderOperationTimeout('恢复位置')).toBeInstanceOf(Error);});
it('超时后封闭队列，底层pending未结束时不得启动下一份操作',async()=>{
 vi.useFakeTimers();const queue=createReaderOperationQueue(new AbortController().signal),next=vi.fn(async()=>{});
 const a=queue.run('首章',()=>new Promise(()=>{})),b=queue.run('目录',next);
 const aa=expect(a).rejects.toBeInstanceOf(ReaderOperationTimeout),bb=expect(b).rejects.toBeInstanceOf(ReaderOperationTimeout);
 await vi.advanceTimersByTimeAsync(20000);await aa;await bb;expect(next).not.toHaveBeenCalled();expect(vi.getTimerCount()).toBe(0);
});
