import {mkdtemp,rm} from 'node:fs/promises';
import path from 'node:path';import os from 'node:os';import JSZip from 'jszip';import sharp from 'sharp';import {NextRequest} from 'next/server';import {beforeEach,afterEach,describe,expect,it,vi} from 'vitest';
import type {createDatabase as CreateDatabase} from '@/lib/db';
const state=vi.hoisted(()=>({db:undefined as ReturnType<typeof CreateDatabase>|undefined}));
vi.mock('@/lib/db',async original=>{const actual=await original<typeof import('@/lib/db')>();return {...actual,getDb:()=>{if(!state.db)throw new Error('测试数据库未初始化');return state.db;}};});
import {createDatabase} from '@/lib/db';import {POST as importBook} from '@/app/api/import/route';import {GET as image} from './route';
let directory:string;
const request=(bytes:Buffer,name='pages.cbz')=>{const form=new FormData();form.set('file',new File([new Uint8Array(bytes)],name));return new NextRequest('http://localhost/api/import',{method:'POST',body:form});};
async function cbz(){const zip=new JSZip();const first=await sharp({create:{width:13,height:17,channels:3,background:'#aa2233'}}).png().toBuffer(),second=await sharp({create:{width:19,height:23,channels:3,background:'#2244aa'}}).jpeg().toBuffer();zip.file('10.jpg',second);zip.file('2.png',first);zip.file('ComicInfo.xml','<ComicInfo/>');return {bytes:await zip.generateAsync({type:'nodebuffer',compression:'DEFLATE'}),first,second};}
beforeEach(async()=>{directory=await mkdtemp(path.join(os.tmpdir(),'judu-cbz-route-'));vi.stubEnv('JUDU_DATA_DIR',directory);state.db=createDatabase();vi.spyOn(console,'error').mockImplementation(()=>{});});
afterEach(async()=>{state.db?.close();state.db=undefined;vi.restoreAllMocks();vi.unstubAllEnvs();const resolved=path.resolve(directory);if(path.dirname(resolved)!==path.resolve(os.tmpdir())||!path.basename(resolved).startsWith('judu-cbz-route-'))throw new Error('不安全测试清理');await rm(resolved,{recursive:true,force:true});});
describe('CBZ原件图片页版本绑定',()=>{
 it('导入→按自然页序读取原始图片字节，且不产生正文段落',async()=>{const fixture=await cbz(),response=await importBook(request(fixture.bytes)),book=await response.json();expect(response.status).toBe(200);expect(book.chapters.map((chapter:{title:string})=>chapter.title)).toEqual(['第 1 页 · 2.png','第 2 页 · 10.jpg']);expect(book.chapters.every((chapter:{paragraphs:unknown[]})=>chapter.paragraphs.length===0)).toBe(true);
  const first=await image(new Request('http://localhost/api/books/x/image?editionId='+book.editionId+'&page=1'),{params:Promise.resolve({bookId:book.id})}),second=await image(new Request('http://localhost/api/books/x/image?editionId='+book.editionId+'&page=2'),{params:Promise.resolve({bookId:book.id})});expect(first.status).toBe(200);expect(second.status).toBe(200);expect(Buffer.from(await first.arrayBuffer())).toEqual(fixture.first);expect(Buffer.from(await second.arrayBuffer())).toEqual(fixture.second);expect(first.headers.get('content-type')).toBe('image/png');expect(first.headers.get('x-judu-image-width')).toBe('13');expect(second.headers.get('x-judu-image-height')).toBe('23');
 });
 it('错误页码、错误版本、非CBZ版本和额外查询参数均拒绝',async()=>{const fixture=await cbz(),book=await (await importBook(request(fixture.bytes))).json();expect((await image(new Request('http://localhost/api/books/x/image?editionId='+book.editionId+'&page=3'),{params:Promise.resolve({bookId:book.id})})).status).toBe(404);expect((await image(new Request('http://localhost/api/books/x/image?editionId='+book.editionId+'&page=1&x=y'),{params:Promise.resolve({bookId:book.id})})).status).toBe(400);expect((await image(new Request('http://localhost/api/books/x/image?editionId='+book.editionId+'&page=1'),{params:Promise.resolve({bookId:'other'})})).status).toBe(404);expect((await image(new Request('http://localhost/api/books/x/image?editionId=bad&page=1'),{params:Promise.resolve({bookId:book.id})})).status).toBe(404);});
 it('原件校验失败返回可恢复错误，不交付任意ZIP成员',async()=>{const fixture=await cbz(),book=await (await importBook(request(fixture.bytes))).json();state.db!.prepare('UPDATE editions SET original_hash=? WHERE id=?').run('0'.repeat(64),book.editionId);const response=await image(new Request('http://localhost/api/books/x/image?editionId='+book.editionId+'&page=1'),{params:Promise.resolve({bookId:book.id})});expect(response.status).toBe(409);expect(await response.json()).toHaveProperty('error');});
});
