// @vitest-environment jsdom
import {act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {beforeEach,afterEach,it,expect,vi} from 'vitest';import {BookShelfAction} from './book-shelf-action';
let host:HTMLDivElement,root:Root;const fetcher=vi.fn<typeof fetch>(),changed=vi.fn();
beforeEach(()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('fetch',fetcher);fetcher.mockReset();changed.mockReset();host=document.createElement('div');document.body.append(host);root=createRoot(host);});afterEach(()=>{act(()=>root.unmount());host.remove();vi.unstubAllGlobals();vi.restoreAllMocks();});
const render=async(archived=false,disabled=false)=>act(async()=>root.render(<BookShelfAction bookId="a" title="书名" archived={archived} disabled={disabled} onChanged={changed}/>));
const click=async(text:string)=>act(async()=>Array.from(host.querySelectorAll('button')).find(b=>b.textContent===text)!.click());
it('先确认且可取消，确认后只发送指定BookID的下架请求',async()=>{await render();await click('下架');expect(fetcher).not.toHaveBeenCalled();expect(host.textContent).toContain('原文件、标注、笔记、对话和向量索引均保留');await click('取消');expect(fetcher).not.toHaveBeenCalled();await click('下架');fetcher.mockResolvedValue(Response.json({bookId:'a',archived:true}));await click('确认下架');expect(fetcher).toHaveBeenCalledWith('/api/books/a/shelf',expect.objectContaining({method:'PATCH',body:JSON.stringify({archived:true})}));expect(changed).toHaveBeenCalledTimes(1);});
it('失败保留确认入口，显示可恢复错误；不假装已下架',async()=>{vi.spyOn(console,'error').mockImplementation(()=>{});await render();await click('下架');fetcher.mockResolvedValue(Response.json({error:'保存失败'},{status:500}));await click('确认下架');expect(host.querySelector('[role=alert]')?.textContent).toContain('保存失败');expect(changed).not.toHaveBeenCalled();expect(host.textContent).toContain('确认下架');});
it('恢复发送false；生成中禁用操作',async()=>{await render(true,true);await click('恢复上架');expect(fetcher).not.toHaveBeenCalled();await render(true);fetcher.mockResolvedValue(Response.json({bookId:'a',archived:false}));await click('恢复上架');expect(fetcher.mock.calls[0][1]?.body).toBe(JSON.stringify({archived:false}));expect(changed).toHaveBeenCalledOnce();});
