"use client";
import {useEffect,useState} from 'react';
import styles from '@/app/settings/settings.module.css';
export function EmbeddingSettings(){
 const [agentSemanticEnabled,setAgentSemanticEnabled]=useState(true);
 const [key,setKey]=useState(''),[configured,setConfigured]=useState(false),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const controller=new AbortController();void fetch('/api/settings/embedding',{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error('读取向量配置失败');const data=await response.json();setConfigured(data.hasApiKey===true);setAgentSemanticEnabled(data.agentSemanticEnabled!==false);}).catch((error:unknown)=>{if(!controller.signal.aborted){console.error('读取向量配置失败',error);setNotice('向量配置读取失败，请刷新重试');}});return()=>controller.abort();},[]);
 async function run(test:boolean){setBusy(true);setNotice('处理中…');try{const response=await fetch('/api/settings/embedding',{method:test?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(test?{}:{apiKey:key})});const data=await response.json();if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'操作失败');if(!test){setConfigured(true);setKey('');}setNotice(test?'向量服务连接成功':'向量密钥已保存，仅服务端可读取');}catch(error:unknown){console.error('向量配置操作失败',error);setNotice(error instanceof Error?error.message:'操作失败');}finally{setBusy(false);}}
 async function toggleAgent(enabled:boolean){setBusy(true);try{const response=await fetch('/api/settings/embedding',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({agentSemanticEnabled:enabled})});if(!response.ok)throw new Error('保存自动检索设置失败');setAgentSemanticEnabled(enabled);setNotice(enabled?'AI 可按需语义检索已索引书籍':'AI 将仅使用本地关键词检索');}catch(error:unknown){console.error('保存自动检索设置失败',error);setNotice('保存失败，请重试');}finally{setBusy(false);}}
 return <section className={styles.card}><h2>向量索引与语义搜索</h2><p>SiliconFlow · Qwen/Qwen3-Embedding-8B · 1024 维</p><p className={styles.hint}>独立于聊天模型。建索引会把本书文字发送至 SiliconFlow，语义搜索会发送查询文字，可能产生 API 费用。向量保存在本地书库；在阅读器“书内搜索”中手动建立，可暂停后继续。不会自动上传整本书。</p><label><input type="checkbox" checked={agentSemanticEnabled} disabled={busy} onChange={event=>void toggleAgent(event.target.checked)}/>允许 AI 按需使用语义检索</label><p className={styles.hint}>仅限已建立索引的当前书籍。开启后 AI 可将改写的检索查询发送至 SiliconFlow（可能计费）；不发送整段对话，不自动建库。关闭后仅使用本地关键词。</p><label>向量 API Key<input aria-label="向量 API Key" type="password" autoComplete="off" value={key} onChange={event=>setKey(event.target.value)} placeholder={configured?'已配置，输入新 Key 可替换':'请输入 SiliconFlow API Key'}/></label><div className={styles.actions}><button disabled={busy||!key.trim()} onClick={()=>void run(false)}>保存向量配置</button><button disabled={busy||!configured} onClick={()=>void run(true)}>测试向量连接</button></div><p role="status">{notice|| (configured?'向量服务已配置':'尚未配置向量密钥')}</p></section>;
}
