// @vitest-environment jsdom
import { act } from "react";import {createRoot} from "react-dom/client";import {expect,it,vi} from "vitest";
import {RetrievalActivity} from './retrieval-activity';import type {ChatMessage} from '@/lib/chat-stream';
it('默认折叠、展示真实查询策略来源并可定位，失败或取消不显示成功',async()=>{
 vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);const element=document.createElement('div'),root=createRoot(element),jump=vi.fn();
 const message:ChatMessage={id:'m',role:'assistant',content:'答案',status:'completed',tools:[{id:'t',name:'search_book',status:'completed',result:{ok:true,sources:[{sourceId:'book:e:paragraph:p',paragraphId:'p',chapterTitle:'土地财政',text:'地方政府利用土地。'}],retrieval:{version:1,requestedMode:'auto',effectiveMode:'hybrid',queries:['地方政府'],branches:[{query:'地方政府',strategy:'semantic',status:'completed',count:2,durationMs:20,promptTokens:9}],durationMs:22,sourceCount:1,degraded:false}}}]};
 try{await act(async()=>root.render(<RetrievalActivity message={message} onOpenCitation={jump}/>));const card=element.querySelector('details')!;expect(card.open).toBe(false);expect(element.textContent).toContain('1 段参考');expect(element.textContent).toContain('9 输入 tokens');await act(async()=>element.querySelector('button')!.click());expect(jump).toHaveBeenCalledWith('p','地方政府利用土地。','m');await act(async()=>root.render(<RetrievalActivity message={{...message,status:'error',tools:[{id:'t',name:'search_book',status:'running'}]}}/>));expect(element.textContent).toContain('检索已中断');expect(element.textContent).not.toContain('已检索本书');}finally{await act(async()=>root.unmount());vi.unstubAllGlobals();}
});
it('渠道独立折叠、按真实命中归类；双路计数去重，旧记录不猜来源',async()=>{
 vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);const host=document.createElement('div'),root=createRoot(host);
 const source=(id:string,channels?:string[])=>({sourceId:'book:e:paragraph:'+id,paragraphId:id,chapterTitle:id,text:id+'原文'.repeat(180),...(channels?{channels}:{})});
 const message:ChatMessage={id:'m',role:'assistant',content:'答案',status:'completed',tools:[{id:'search',name:'search_book',status:'completed',result:{ok:true,sources:[source('keyword',['keyword']),source('semantic',['semantic']),source('both',['keyword','semantic']),source('legacy')],retrieval:{version:1,requestedMode:'auto',effectiveMode:'hybrid',queries:['测试'],branches:[{query:'测试',strategy:'keyword',status:'completed',count:2,durationMs:5},{query:'测试',strategy:'semantic',status:'completed',count:2,durationMs:8}],durationMs:8,sourceCount:4,degraded:false}}},{id:'read',name:'read_source',status:'completed',result:{ok:true,sources:[source('neighbor')]}}]};
 try{await act(async()=>root.render(<RetrievalActivity message={message}/>));const card=host.querySelector<HTMLDetailsElement>('[data-testid="retrieval-activity"]')!;expect(card.open).toBe(false);expect(card.querySelector('summary')!.textContent).toContain('5 段参考');await act(async()=>card.querySelector('summary')!.click());expect(card.open).toBe(true);
 const group=(name:string)=>host.querySelector<HTMLDetailsElement>(`[data-retrieval-channel="${name}"]`)!;
 for(const name of ['keyword','semantic','reading','unrecorded'])expect(group(name).open).toBe(false);
 expect(group('keyword').textContent).toContain('keyword');expect(group('keyword').textContent).not.toContain('semantic原文');expect(group('semantic').textContent).toContain('semantic');expect(group('semantic').textContent).not.toContain('legacy');expect(group('keyword').textContent).toContain('双路命中');expect(group('unrecorded').textContent).toContain('未保存命中渠道');expect(group('reading').textContent).toContain('neighbor');
 await act(async()=>group('keyword').querySelector('summary')!.click());expect(group('keyword').open).toBe(true);expect(group('semantic').open).toBe(false);
 const snippet=group('keyword').querySelector('ol[aria-label$="来源"] details') as HTMLDetailsElement;expect(snippet.open).toBe(false);await act(async()=>snippet.querySelector('summary')!.click());expect(snippet.querySelector('blockquote')!.textContent).toHaveLength(220);const expand=snippet.querySelector('button')!;await act(async()=>expand.click());expect(snippet.querySelector('blockquote')!.textContent!.length).toBeGreaterThan(220);
 }finally{await act(async()=>root.unmount());vi.unstubAllGlobals();}
});
it('旧混合记录不把未知渠道误写成未入选',async()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);const host=document.createElement('div'),root=createRoot(host);const message:ChatMessage={role:'assistant',content:'回答',status:'completed',tools:[{id:'old',name:'search_book',status:'completed',result:{ok:true,sources:[{sourceId:'book:e:paragraph:p',paragraphId:'p',chapterTitle:'历史章',text:'已进入参考的原文'}],retrieval:{version:1,requestedMode:'auto',effectiveMode:'hybrid',queries:['词'],branches:[{query:'词',strategy:'keyword',status:'completed',count:3,durationMs:1},{query:'词',strategy:'semantic',status:'completed',count:3,durationMs:2}],durationMs:2,sourceCount:1,degraded:false}}}]};try{await act(async()=>root.render(<RetrievalActivity message={message}/>));const keyword=host.querySelector('[data-retrieval-channel="keyword"]')!;expect(keyword.textContent).toContain('旧记录未保存来源渠道');expect(keyword.textContent).not.toContain('未进入');}finally{await act(async()=>root.unmount());vi.unstubAllGlobals();}});
