// @vitest-environment jsdom
import {describe,it,expect} from 'vitest';
import {renderToStaticMarkup} from 'react-dom/server';
import {SectionReadingAction} from './section-reading-action';
const chapter={id:'c',title:'标题',paragraphs:[{id:'p',text:'正文'}]};
describe('本节入口',()=>{it('有已有记录则查看，避免重复生成',()=>{expect(renderToStaticMarkup(<SectionReadingAction chapter={chapter} onStart={()=>{}} onOpenExisting={()=>{}}/>)).toContain('查看本节句读');});it('无文字不提供伪句读',()=>{expect(renderToStaticMarkup(<SectionReadingAction chapter={{...chapter,paragraphs:[]}} onStart={()=>{}}/>)).toBe('');});});

import {act} from 'react';import {createRoot} from 'react-dom/client';import {vi} from 'vitest';
it('已有入口悬停才展开操作，键盘可达，重做先确认且不会直接生成',async()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);const host=document.createElement('div'),root=createRoot(host),start=vi.fn(),view=vi.fn();document.body.append(host);Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:()=>{}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:()=>{}});const modal=vi.spyOn(HTMLDialogElement.prototype,'showModal').mockImplementation(function(this:HTMLDialogElement){this.open=true;});const close=vi.spyOn(HTMLDialogElement.prototype,'close').mockImplementation(function(this:HTMLDialogElement){this.open=false;});try{await act(async()=>root.render(<SectionReadingAction chapter={chapter} readingStyle="whole" onStart={start} onOpenExisting={view}/>));expect(host.querySelectorAll('button')).toHaveLength(1);await act(async()=>host.querySelector('button')!.dispatchEvent(new MouseEvent('mouseover',{bubbles:true})));expect(host.querySelector('[aria-label="本节句读操作"]')).not.toBeNull();expect(host.textContent).toContain('整段句读');expect(start).not.toHaveBeenCalled();await act(async()=>[...host.querySelectorAll('button')].find(b=>b.textContent==='按当前设置重新句读')!.click());expect(modal).toHaveBeenCalled();expect(start).not.toHaveBeenCalled();expect(host.textContent).toContain('以自然段为最小单位');await act(async()=>[...host.querySelectorAll('button')].find(b=>b.textContent==='开始本节句读')!.click());expect(start).toHaveBeenCalledWith(expect.objectContaining({text:'正文'}),'c');}finally{await act(async()=>root.unmount());host.remove();modal.mockRestore();close.mockRestore();vi.unstubAllGlobals();}});

it('浮窗内按Escape关闭并回到入口，不因恢复焦点重新打开',async()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);const host=document.createElement('div'),root=createRoot(host);document.body.append(host);try{await act(async()=>root.render(<SectionReadingAction chapter={chapter} onStart={()=>{}} onOpenExisting={()=>{}}/>));const trigger=host.querySelector('button')!;await act(async()=>trigger.focus());const menu=host.querySelector('[aria-label="本节句读操作"]')!;await act(async()=>menu.querySelector('button')!.focus());await act(async()=>document.activeElement!.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));expect(host.querySelector('[aria-label="本节句读操作"]')).toBeNull();expect(document.activeElement).toBe(trigger);}finally{await act(async()=>root.unmount());host.remove();vi.unstubAllGlobals();}});
