"use client";
import {useEffect,useRef,useState} from 'react';
type Status={paragraphCount:number;indexedCount:number;chunkCount:number;indexedChunkCount:number;vectorIndexed:boolean;configured?:boolean;note:string};
export function VectorIndexControls({editionId,onReady}:{editionId?:string;onReady:()=>void}){
 const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[consent,setConsent]=useState(false);
 const active=useRef<AbortController|null>(null),stop=useRef(false),generation=useRef(0);
 // WHY：版本变化必须清空旧书授权和进度，不能将 A 书同意状态沿用到 B 书。
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const controller=new AbortController();const version=++generation.current;active.current?.abort();stop.current=true;setBusy(false);setStatus(null);setConsent(false);setNotice('');if(editionId)void fetch('/api/search/status?engine=local-vector&editionId='+encodeURIComponent(editionId),{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error('读取向量索引状态失败');return response.json() as Promise<Status>;}).then(data=>{if(version===generation.current)setStatus(data);}).catch((error:unknown)=>{if(!controller.signal.aborted){console.error('读取索引状态失败',error);setNotice('读取索引状态失败，请重新打开本书');}});return()=>{generation.current=version+1;controller.abort();active.current?.abort();stop.current=true;};},[editionId]);
 async function build(){if(!editionId||!consent||busy)return;const version=generation.current,controller=new AbortController();active.current=controller;stop.current=false;setBusy(true);setNotice('正在建立索引…');try{while(!stop.current){const response=await fetch('/api/search/index',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({editionId,consent:true}),signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'索引失败');if(version!==generation.current)return;setStatus({...data,configured:true});if(data.vectorIndexed||data.chunkCount===0){setNotice(data.vectorIndexed?'本书向量索引已完成':'本书没有可索引文字');onReady();return;}}if(version===generation.current)setNotice('已暂停，已完成的切块已保存，可继续建立');}catch(error:unknown){if(!controller.signal.aborted&&version===generation.current){console.error('索引建立失败',error);setNotice(error instanceof Error?error.message:'建立失败，可重试继续');}}finally{if(version===generation.current){setBusy(false);active.current=null;}}}
 return <div className="vector-index-controls"><p>{status?.vectorIndexed?'向量索引已就绪':'本地向量索引'} · {status?.indexedChunkCount??0}/{status?.chunkCount??0} 块</p>{status&&<progress aria-label="向量索引进度" max={Math.max(1,status.chunkCount)} value={status.indexedChunkCount}/>}<label><input type="checkbox" checked={consent} disabled={busy} onChange={event=>setConsent(event.target.checked)}/>同意将本书文字发送至 SiliconFlow 建立向量索引（可能计费）</label><button type="button" disabled={busy||!editionId||!consent||!status?.configured||status.vectorIndexed||status.chunkCount===0} onClick={()=>void build()}>建立 / 继续向量索引</button>{busy&&<button type="button" onClick={()=>{stop.current=true;setNotice('将在当前批次完成后暂停…');}}>暂停索引</button>}{status&&!status.configured&&<a href="/settings">先配置向量服务</a>}{notice&&<p role="status">{notice}</p>}</div>;
}
